import uuid
from pathlib import Path
from typing import Dict, List

from generator.modular import generate_module_structure
from generator.common.providers import get_provider_config
from generator.common.versions import terraform_versions


def generate_terraform(architecture: dict) -> dict:
    """
    Takes validated architecture JSON
    Generates modular Terraform code structure

    Structure:
    /terraform
      ├── main.tf          # Module calls
      ├── variables.tf     # Root variables
      ├── outputs.tf       # Root outputs
      ├── providers.tf     # Provider configuration
      ├── versions.tf      # Terraform versions
      └── modules/
          ├── resource-1/  # Individual resource modules
          │   ├── main.tf
          │   ├── variables.tf
          │   └── outputs.tf
          └── resource-2/
              ├── main.tf
              ├── variables.tf
              └── outputs.tf
    """

    request_id = str(uuid.uuid4())
    base_path = Path(f"/tmp/ai-iac/{request_id}/terraform")
    base_path.mkdir(parents=True, exist_ok=True)

    resources = architecture.get("resources", [])

    if not resources:
        raise ValueError("No resources found in architecture")

    # Detect cloud provider
    provider = detect_provider(resources)

    # Generate module structure for each resource
    module_configs = []
    for resource in resources:
        module_config = generate_module_structure(base_path, resource)
        module_configs.append(module_config)

    # Generate root main.tf with module calls
    generate_root_main(base_path, module_configs)

    # Generate root variables.tf
    generate_root_variables(base_path, module_configs)

    # Generate root outputs.tf
    generate_root_outputs(base_path, module_configs)

    # Generate providers.tf
    (base_path / "providers.tf").write_text(get_provider_config(provider))

    # Generate versions.tf
    (base_path / "versions.tf").write_text(terraform_versions())

    # Read generated main.tf for return
    terraform_code = (base_path / "main.tf").read_text()

    return {
        "request_id": request_id,
        "terraform_path": str(base_path),
        "terraform_code": terraform_code,
        "resources": resources,
        "provider": provider
    }


def detect_provider(resources: List[Dict]) -> str:
    """Detect cloud provider from resources"""
    for resource in resources:
        resource_type = resource.get('type', '')
        if resource_type.startswith('aws_'):
            return 'aws'
        elif resource_type.startswith('azure_'):
            return 'azure'
        elif resource_type.startswith('gcp_'):
            return 'gcp'
    return 'aws'  # Default


def generate_root_main(base_path: Path, module_configs: List[Dict]):
    """Generate root main.tf with module calls"""
    lines = [
        "# Auto-generated Terraform configuration",
        "# Generated by AI IaC Platform\n",
        "locals {",
        "  common_tags = {",
        '    ManagedBy = "AI-IaC-Platform"',
        '    Environment = var.environment',
        "  }",
        "}\n"
    ]

    # Group modules by type for proper dependency order
    vpc_modules = [m for m in module_configs if 'vpc' in m['resource_type'].lower() or 'vnet' in m['resource_type'].lower()]
    other_modules = [m for m in module_configs if m not in vpc_modules]

    # VPC/VNet modules first (foundational)
    for module in vpc_modules:
        lines.append(f'module "{module["name"]}" {{')
        lines.append(f'  source = "{module["source"]}"')
        lines.append("")
        lines.append("  common_tags = local.common_tags")
        lines.append("}\n")

    # Other modules with dependencies
    for module in other_modules:
        lines.append(f'module "{module["name"]}" {{')
        lines.append(f'  source = "{module["source"]}"')
        lines.append("")

        # Add VPC dependency if exists
        if vpc_modules:
            vpc_module = vpc_modules[0]
            lines.append(f'  vpc_id     = module.{vpc_module["name"]}.vpc_id')
            lines.append(f'  subnet_ids = module.{vpc_module["name"]}.private_subnet_ids')
            lines.append("")

        lines.append("  common_tags = local.common_tags")
        lines.append("}\n")

    (base_path / "main.tf").write_text("\n".join(lines))


def generate_root_variables(base_path: Path, module_configs: List[Dict]):
    """Generate root variables.tf"""
    content = '''variable "environment" {
  description = "Environment name (dev, staging, prod)"
  type        = string
  default     = "dev"
}

variable "region" {
  description = "Cloud provider region"
  type        = string
  default     = "ap-south-1"  # Change based on provider
}

variable "project_name" {
  description = "Project name for resource naming"
  type        = string
  default     = "ai-iac-platform"
}
'''
    (base_path / "variables.tf").write_text(content)


def generate_root_outputs(base_path: Path, module_configs: List[Dict]):
    """Generate root outputs.tf"""
    lines = ["# Outputs from all modules\n"]

    for module in module_configs:
        module_name = module['name']
        resource_type = module['resource_type']

        if 'vpc' in resource_type.lower():
            lines.append(f'output "{module_name}_vpc_id" {{')
            lines.append(f'  description = "VPC ID from {module_name}"')
            lines.append(f'  value       = module.{module_name}.vpc_id')
            lines.append("}\n")
        elif 'eks' in resource_type.lower() or 'aks' in resource_type.lower() or 'gke' in resource_type.lower():
            lines.append(f'output "{module_name}_cluster_endpoint" {{')
            lines.append(f'  description = "Cluster endpoint from {module_name}"')
            lines.append(f'  value       = module.{module_name}.cluster_endpoint')
            lines.append('  sensitive   = true')
            lines.append("}\n")
        elif 'alb' in resource_type.lower():
            lines.append(f'output "{module_name}_dns_name" {{')
            lines.append(f'  description = "DNS name from {module_name}"')
            lines.append(f'  value       = module.{module_name}.alb_dns_name')
            lines.append("}\n")

    (base_path / "outputs.tf").write_text("\n".join(lines))
